import localFont from 'next/font/local';
import type { Metadata } from 'next';
import StyledComponentsRegistry from '@/lib/registry';
import GlobalStyle from '@/app/GlobalStyle';

export const metadata: Metadata = {
  title: 'Test Project',
  description: 'Generated by create next app',
};

const sora = localFont({
  src: [
    {
      path: './fonts/sora-thin.woff2',
      weight: '100',
      // display: 'swap',
    },
    {
      path: './fonts/sora-thin.woff',
      weight: '100',
      // display: 'swap',
    },
    {
      path: './fonts/sora-light.woff2',
      weight: '300',
      // display: 'swap',
    },
    {
      path: './fonts/sora-light.woff',
      weight: '300',
      // display: 'swap',
    },
    {
      path: './fonts/sora-regular.woff2',
      weight: '400',
      // display: 'swap',
    },
    {
      path: './fonts/sora-regular.woff',
      weight: '400',
      // display: 'swap',
    },
    {
      path: './fonts/sora-medium.woff2',
      weight: '500',
      // display: 'swap',
    },
    {
      path: './fonts/sora-medium.woff',
      weight: '500',
      // display: 'swap',
    },
    {
      path: './fonts/sora-semi-bold.woff2',
      weight: '600',
      // display: 'swap',
    },
    {
      path: './fonts/sora-semi-bold.woff',
      weight: '600',
      // display: 'swap',
    },
    {
      path: './fonts/sora-bold.woff2',
      weight: '700',
      // display: 'swap',
    },
    {
      path: './fonts/sora-bold.woff',
      weight: '700',
      // display: 'swap',
    },
    {
      path: './fonts/sora-extra-bold.woff2',
      weight: '800',
      // display: 'swap',
    },
    {
      path: './fonts/sora-extra-bold.woff',
      weight: '800',
      // display: 'swap',
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <StyledComponentsRegistry>
          <GlobalStyle />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
